apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: TBD
  annotations:
    fluxcd.io/ignore: "false"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80