apiVersion: v1
kind: Pod
metadata:
  annotations:
    fluxcd.io/ignore: 'false'
  name: nginx
  namespace: first
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
    ports:
    - containerPort: 80
